name: llvm-mingw

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    strategy:
      matrix:
        os:
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        shell: bash
        run: |
          . setup-llvm-mingw.bash
          cd build
          for arch in i686 x86_64; do
            rm -f ovbase-$arch/CmakeCache.txt
            cmake -S .. -B ovbase-$arch --preset debug \
              -DFORMAT_SOURCES=ON \
              -DCMAKE_INSTALL_PREFIX=local \
              -DSKIP_OVTHREADS_TEST=OFF \
              -DCMAKE_TOOLCHAIN_FILE=cmake/llvm-mingw.cmake \
              -DCMAKE_C_COMPILER=$arch-w64-mingw32-clang
            cmake --build ovbase-$arch
            ctest --test-dir ovbase-$arch --output-on-failure --output-junit testlog.xml
          done
