name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - msystem: MINGW32
            arch: i686
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: git mingw-w64-${{ matrix.arch }}-tools mingw-w64-${{ matrix.arch }}-ninja mingw-w64-${{ matrix.arch }}-clang mingw-w64-${{ matrix.arch }}-compiler-rt mingw-w64-${{ matrix.arch }}-cmake
      - name: Run ninja
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake -GNinja .. && ninja && ctest --output-junit testlog.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests
          path: build/testlog.xml
          reporter: java-junit
