name: ubuntu

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup
        run: |
          sudo apt install -y cmake ninja-build clang clang-format lld
      - name: Build
        run: |
          mkdir build
          cd build
          rm -rf CmakeCache.txt && cmake -GNinja -DCMAKE_C_COMPILER=clang -DFORMAT_SOURCES=OFF -DSKIP_OVTHREADS_TEST=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. && cmake --build . && ctest --output-on-failure --output-junit testlog.xml
