name: ubuntu

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup
        run: |
          sudo apt install -y cmake ninja-build clang clang-format lld
      - name: Build
        run: |
          mkdir -p build/ovbase
          cd build
          rm -f ovbase/CmakeCache.txt && cmake -S .. -B ovbase --preset debug -DFORMAT_SOURCES=ON -DCMAKE_INSTALL_PREFIX=local -DSKIP_OVTHREADS_TEST=OFF -DCMAKE_C_COMPILER=clang && \
          cmake --build ovbase && ctest --test-dir ovbase --output-on-failure --output-junit testlog.xml
