name: ubuntu

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Build
        run: |
          mkdir -p build/ubuntu-ovbase-debug
          sudo docker run --net host -i -v .:/root/ovbase ubuntu:jammy /bin/bash -c 'apt update && apt install -y cmake ninja-build clang clang-format lld && cd /root/ovbase && ARCHDIR="x86_64_ubuntu" bash build.bash --no-install-tools --debug --no-format'
