name: wasi

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup
        run: |
          sudo apt install -y git wget tar cmake ninja-build clang-format xz-utils
      - name: Build
        run: |
          mkdir build
          cd build
          wget https://github.com/bytecodealliance/wasmtime/releases/download/v8.0.1/wasmtime-v8.0.1-x86_64-linux.tar.xz
          tar Jxf wasmtime-v8.0.1-x86_64-linux.tar.xz
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-20/wasi-sdk-20.0-linux.tar.gz
          tar zxf wasi-sdk-20.0-linux.tar.gz
          export PATH="$(pwd)/wasmtime-v8.0.1-x86_64-linux:$PATH"
          rm -rf CmakeCache.txt && CC="$(pwd)/wasi-sdk-20.0/bin/clang --target=wasm32-wasi-threads --sysroot=$(pwd)/wasi-sdk-20.0/share/wasi-sysroot -pthread" cmake -GNinja -DFORMAT_SOURCES=OFF -DSKIP_OVTHREADS_TEST=OFF -DWASI_THREADS=ON .. && cmake --build . && ctest --output-on-failure --output-junit testlog.xml
