name: windows-msys2

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - msystem: MINGW64
            arch: x86_64
          - msystem: MINGW32
            arch: i686
          - msystem: CLANG64
            arch: clang-x86_64
          - msystem: CLANG32
            arch: clang-i686
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: >-
            mingw-w64-${{ matrix.arch }}-cmake
            mingw-w64-${{ matrix.arch }}-ninja
            mingw-w64-${{ matrix.arch }}-clang
            mingw-w64-${{ matrix.arch }}-compiler-rt
            mingw-w64-${{ matrix.arch }}-lld
      - name: Build
        shell: msys2 {0}
        run: |
          mkdir -p build/ovbase
          cd build
          rm -f ovbase/CmakeCache.txt ovbase/local/build/mimalloc/CmakeCache.txt && cmake -S .. -B ovbase --preset debug -DFORMAT_SOURCES=ON -DUSE_MIMALLOC=ON -DCMAKE_INSTALL_PREFIX=local && \
          cmake --build ovbase && ctest --test-dir ovbase --output-on-failure --output-junit testlog.xml
